import Head from 'next/head'
import EspeciesCard from '../components/EspeciesCard'
import especiesData from '../data/especies.json'
import PublishersCard from '../components/PublishersCard'
import publishersData from '../data/publishers.json'
import MenuExplorer from '../components/MenuExplorer'
import biologicTree from './../data/arbol_grupos_biologicos.json'
import interestTree from './../data/arbol_grupos_interes.json'
import searchBiologicTree from './../data/narino_gr_bio.json'
import { Carousel } from '../lib/Carousel'
import { SimpleSlider } from '../lib/Slider'

export default function Home () {
  return (
    <>
      <Head>
        <title>Humbolt | Biodiversidad</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='bg-banner-home bg-cover bg-center pt-[279px] pb-[203px]'>
        <div className='mx-auto max-w-[950px]'>
          <div className='flex flex-col items-center justify-center lg:flex-row lg:justify-between text-white gap-y-8'>
            <div className='text-center lg:text-left'>
              <p className='font-barlow-condensed text-5xl lg:text-6xl xl:text-7xl 2xl:text-8xl 3xl:text-[120px] font-semibold -ml-2'>
                10.317
              </p>
              <p className='-mt-2'>
                Especies registradas
              </p>
              <h1 className='text-4xl 3xl:text-[52px] mt-5'>
                Nariño
              </h1>
            </div>
            <div className='w-full max-w-[283px]'>
              <img src="/images/home-map.png" alt="home map" />
            </div>
          </div>
        </div>
      </div>

      <div className='py-20 bg-white-2'>
        <div className='mx-auto w-10/12 max-w-screen-xl'>
          <div className='flex flex-col items-center gap-y-8 lg:flex-row lg:justify-between lg:gap-x-12'>
            <div className='lg:w-6/12'>
              <div className='flex flex-col gap-y-20 lg:flex-row lg:justify-between lg:gap-x-12'>
                {
                  especiesData.map((item, index) => <EspeciesCard key={`especies-item-${index + 1}`} {...item} />)
                }
              </div>
            </div>
            <div className='lg:w-6/12 max-w-[483px]'>
              <p className='3xl:text-lg'>
                Especies mariLorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minimad as veniam, quis nostrud Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut ad laoreet dolore magna.
              </p>
            </div>
          </div>
        </div>
      </div>

      <div className='bg-white-3 pb-20'>
        <div className='mx-auto w-10/12 max-w-screen-xl relative'>
          <SimpleSlider dots>
            <div className='px-5'>
              <div className='py-12 lg:py-16 xl:py-20 '>
                <div className='flex flex-col items-center gap-y-8 lg:flex-row lg:justify-between lg:gap-x-12'>
                  <div className='lg:w-6/12 max-w-[586px]'>
                    <h2 className='text-black-2 font-black text-3xl 3xl:text-4xl'>
                      Nariño vs. Colombia
                    </h2>
                    <p className='3xl:text-lg mt-10'>
                      Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreetee dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper ad suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolor.
                    </p>
                    <p className='3xl:text-lg mt-6'>
                      Lorem ipsum dolor sit amet, cons ectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad ad sf minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea.
                    </p>
                  </div>
                  <div className='lg:w-6/12 max-w-[438px]'>
                    <p className='text-center 3xl:text-lg'>
                      Especies registradas en Nariño vs. especies registradas en Colombia
                    </p>
                    <img className='mx-auto mt-4' src="/images/demo-graphic.svg" alt="demo graphic" />
                  </div>
                </div>
              </div>
            </div>
            <div className='px-5'>
              <div className='grid md:grid-cols-2 lg:grid-cols-12 gap-10'>
                <div className='lg:col-start-1 lg:col-end-6 lg:row-start-1 lg:row-end-4'>
                  <div className='bg-blue-green text-white min-h-full px-[71px] py-[145px]'>
                    <p>
                      <b>Charalá</b>, patrimonio histórico de Colombia y de su Biodiversidad, es el municipio de Santander donde se han observado el mayor número de especies endémicas de Colombia.</p>
                  </div>
                </div>
                <div className='hidden lg:block lg:col-start-6 lg:col-end-8 lg:row-start-1 lg:row-end-4'>
                  <img className='w-full h-full object-cover object-center' src="/images/gallery-1.png" alt="gallery-1" />
                </div>
                <div className='lg:col-start-8 lg:col-end-13 lg:row-start-1 lg:row-end-2'>
                  <div className='bg-blue-green text-white pt-[37px] pb-[34px] px-[108px]'>
                    <p>
                      El 11% de las especies únicas del país que <b>viven en Santander</b> corren el riesgo de desaparecer. Usted puede cuidarlas!
                    </p>
                  </div>
                </div>
                <div className='hidden lg:block lg:col-start-8 lg:col-end-13 lg:row-start-2 lg:row-end-4'>
                  <img className='w-full h-full object-cover object-center' src="/images/gallery-2.png" alt="gallery-2" />
                </div>
                <div className='hidden lg:block lg:lg:col-start-1 lg:col-end-8 lg:row-start-4 lg:row-end-5'>
                  <img className='w-full h-full object-cover object-center' src="/images/gallery-3.png" alt="gallery-3" />
                </div>
                <div className='lg:col-start-8 lg:col-end-13 lg:row-start-4 lg:row-end-5'>
                  <div className='bg-blue-green text-white pt-[37px] pb-[34px] px-[108px]'>
                    <p>
                      <b>El roble colombiano</b>, árbol endémico de los Andes, es la planta con más observaciones en el departamento.
                    </p>
                  </div>
                </div>
              </div>
            </div>
            <div className='px-5'>
              <div className='grid md:grid-cols-2 lg:grid-cols-12 gap-10'>
                <div className='lg:col-start-1 lg:col-end-6'>
                  <div className='bg-blue-green py-20 px-24 text-white'>
                    <p className='3xl:text-lg'>
                      El 11% de las <b>especies únicas</b> del país que viven en <b>Santander</b> corren el riesgo de desaparecer.
                    </p>
                    <p className='3xl:text-lg'>
                      <b>Usted puede cuidarlas!</b>
                    </p>
                  </div>
                </div>
                <div className='lg:col-start-6 lg:col-end-13'>
                  <img className='w-full h-full object-center object-cover' src="/images/gallery-4.png" alt="gallery 4" />
                </div>
                <div className='lg:col-start-1 lg:col-end-8'>
                  <img className='w-full h-full object-center object-cover' src="/images/gallery-5.png" alt="gallery 5" />
                </div>
                <div className='lg:col-start-8 lg:col-end-13'>
                  <div className='bg-blue-green py-20 px-24 text-white'>
                    <p className='3xl:text-lg'>
                      <b>El roble colombiano</b>, árbol endémico de los Andes, es la planta con más observaciones en el departamento.
                    </p>
                    <p className='3xl:text-lg'>
                      <b>Usted puede cuidarlas!</b>
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </SimpleSlider>
        </div>
      </div>

      {/* Arboles de navegacio */}
      <div className='py-12 bg-white-2'>
        <div className='mx-auto w-10/12 max-w-screen-xl'>
          <MenuExplorer tree={biologicTree} search={searchBiologicTree}>
            <MenuExplorer.Title>
              <p className='3xl:text-lg'>
                Conoce las cifras por
              </p>
              <h2 className='font-black text-3xl 3xl:text-4xl'>
                Grupos Biológicos
              </h2>
            </MenuExplorer.Title>
            <MenuExplorer.Tree className='relative mt-[45.52px]' />
            <MenuExplorer.Breadcrumb className=" flex items-center gap-x-2 mt-[30.8px] ml-5" />
            <MenuExplorer.Body className="-mt-10">
              {(selected, info) => (
                <div className='bg-white py-12 lg:py-16 xl:py-20'>
                  <div className='text-center'>
                    <h3 className='font-black text-2xl 3xl:text-3xl'>
                      {selected}
                    </h3>
                  </div>
                  <div className='mx-auto w-10/12 mt-10'>
                    <div className='flex flex-col lg:flex-row items-center justify-between gap-y-8'>
                      <div className='lg:w-1/3 max-w-[216.31px]'>
                        <div className='text-center'>
                          <p className='font-barlow-condensed text-5xl 3xl:text-6xl font-semibold'>
                            {info?.especies_amenazadas_global | 0}
                          </p>
                          <p className='3xl:text-lg'>
                            Especies amenazadas
                          </p>
                          <img className='mx-auto mt-[31.69px]' src="/images/cifras-chart-demo.svg" alt="cifras" />
                          <div className='mt-[25.4px] space-y-[7px]'>
                            <p className='text-sm'>
                              Lorem ipsum dolor sit
                            </p>
                            <p className='text-sm'>
                              Lorem ipsum dolor sit
                            </p>
                            <p className='text-sm'>
                              Lorem ipsum dolor sit
                            </p>
                          </div>
                        </div>
                      </div>
                      <div className='lg:w-1/3 max-w-[216.31px]'>
                        <div className='text-center'>
                          <p className='font-barlow-condensed text-5xl 3xl:text-6xl font-semibold'>
                            {info?.especies_cites | 0}
                          </p>
                          <p className='3xl:text-lg'>
                            Especies CITES
                          </p>
                          <img className='mx-auto mt-[31.69px]' src="/images/cifras-chart-demo.svg" alt="cifras" />
                          <div className='mt-[25.4px] space-y-[7px]'>
                            <p className='text-sm'>
                              Lorem ipsum dolor sit
                            </p>
                            <p className='text-sm'>
                              Lorem ipsum dolor sit
                            </p>
                            <p className='text-sm'>
                              Lorem ipsum dolor sit
                            </p>
                          </div>
                        </div>
                      </div>
                      <div className='lg:w-1/3 max-w-[216.31px]'>
                        <div className='text-center'>
                          <p className='font-barlow-condensed text-5xl 3xl:text-6xl font-semibold'>
                            {info?.especies_endemicas | 0}
                          </p>
                          <p className='3xl:text-lg'>
                            Especies endémicas
                          </p>
                          <img className='mx-auto mt-[31.69px]' src="/images/cifras-chart-demo.svg" alt="cifras" />
                          <div className='mt-[25.4px] space-y-[7px]'>
                            <p className='text-sm'>
                              Lorem ipsum dolor sit
                            </p>
                            <p className='text-sm'>
                              Lorem ipsum dolor sit
                            </p>
                            <p className='text-sm'>
                              Lorem ipsum dolor sit
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              )}
            </MenuExplorer.Body>
          </MenuExplorer>
        </div>
      </div>

      {/* Arboles de navegacio */}
      <div className='py-12 bg-white-2'>
        <div className='mx-auto w-10/12 max-w-screen-xl'>
          <MenuExplorer tree={interestTree} search={searchBiologicTree}>
            <MenuExplorer.Title>
              <p className='3xl:text-lg'>
                Conoce las cifras por
              </p>
              <h2 className='font-black text-3xl 3xl:text-4xl'>
                Grupos de interés
              </h2>
            </MenuExplorer.Title>
            <MenuExplorer.Tree className='relative mt-[45.52px]' />
            <MenuExplorer.Breadcrumb className=" flex items-center gap-x-2 mt-[30.8px] ml-5" />
            <div className='bg-white py-12 lg:py-16 xl:py-20'>
              <div className='text-center'>
                <h3 className='font-black text-2xl 3xl:text-3xl'>
                  Grupos de interés
                </h3>
              </div>
              <div className='mx-auto w-10/12 mt-10'>
                <div className='flex flex-col lg:flex-row items-center justify-between gap-y-8'>
                  <div className='lg:w-1/3 max-w-[216.31px]'>
                    <div className='text-center'>
                      <p className='font-barlow-condensed text-5xl 3xl:text-6xl font-semibold'>
                        86
                      </p>
                      <p className='3xl:text-lg'>
                        Especies amenazadas
                      </p>
                      <img className='mx-auto mt-[31.69px]' src="/images/cifras-chart-demo.svg" alt="cifras" />
                      <div className='mt-[25.4px] space-y-[7px]'>
                        <p className='text-sm'>
                          Lorem ipsum dolor sit
                        </p>
                        <p className='text-sm'>
                          Lorem ipsum dolor sit
                        </p>
                        <p className='text-sm'>
                          Lorem ipsum dolor sit
                        </p>
                      </div>
                    </div>
                  </div>
                  <div className='lg:w-1/3 max-w-[216.31px]'>
                    <div className='text-center'>
                      <p className='font-barlow-condensed text-5xl 3xl:text-6xl font-semibold'>
                        216
                      </p>
                      <p className='3xl:text-lg'>
                        Especies CITES
                      </p>
                      <img className='mx-auto mt-[31.69px]' src="/images/cifras-chart-demo.svg" alt="cifras" />
                      <div className='mt-[25.4px] space-y-[7px]'>
                        <p className='text-sm'>
                          Lorem ipsum dolor sit
                        </p>
                        <p className='text-sm'>
                          Lorem ipsum dolor sit
                        </p>
                        <p className='text-sm'>
                          Lorem ipsum dolor sit
                        </p>
                      </div>
                    </div>
                  </div>
                  <div className='lg:w-1/3 max-w-[216.31px]'>
                    <div className='text-center'>
                      <p className='font-barlow-condensed text-5xl 3xl:text-6xl font-semibold'>
                        41
                      </p>
                      <p className='3xl:text-lg'>
                        Especies endémicas
                      </p>
                      <img className='mx-auto mt-[31.69px]' src="/images/cifras-chart-demo.svg" alt="cifras" />
                      <div className='mt-[25.4px] space-y-[7px]'>
                        <p className='text-sm'>
                          Lorem ipsum dolor sit
                        </p>
                        <p className='text-sm'>
                          Lorem ipsum dolor sit
                        </p>
                        <p className='text-sm'>
                          Lorem ipsum dolor sit
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </MenuExplorer>
        </div>
      </div>

      {/* Arboles de navegacio */}
      <div className='py-12 bg-white-2'>
        <div className='mx-auto w-10/12 max-w-screen-xl'>
          <MenuExplorer tree={interestTree} search={searchBiologicTree}>
            <MenuExplorer.Title>
              <p className='3xl:text-lg'>
                Conoce las cifras por
              </p>
              <h2 className='font-black text-3xl 3xl:text-4xl'>
                Temáticas
              </h2>
            </MenuExplorer.Title>
            <MenuExplorer.Tree className='relative mt-[45.52px]' />
            <MenuExplorer.Breadcrumb className=" flex items-center gap-x-2 mt-[30.8px] ml-5" />
            <div className='bg-white py-12 lg:py-16 xl:py-20'>
              <div className='mx-auto w-10/12 mt-10'>
                <div className='flex flex-col lg:flex-row items-center justify-between gap-y-8'>
                  <div className='lg:w-6/12 max-w-[301px.29px]'>
                    <div className='text-center'>
                      <p className='font-barlow-condensed text-5xl 3xl:text-6xl font-semibold'>
                        15
                      </p>
                      <p className='3xl:text-lg'>
                        Especies registradas
                      </p>
                      <img className='mx-auto mt-[31.69px]' src="/images/cifras-chart-demo.svg" alt="cifras" />
                      <div className='mt-[25.4px] space-y-[7px]'>
                        <p className='text-sm'>
                          Lorem ipsum dolor sit
                        </p>
                        <p className='text-sm'>
                          Lorem ipsum dolor sit
                        </p>
                        <p className='text-sm'>
                          Lorem ipsum dolor sit
                        </p>
                      </div>
                    </div>
                  </div>
                  <div className='lg:w-5/12 max-w-[322px]'>
                    <div>
                      <h3 className='font-bold 3xl:text-lg'>
                        Especies exóticas destacadas
                      </h3>
                      <div>
                        <div className='flex justify-between items-center mt-[35.52px] gap-x-4'>
                          <div className='max-w-[106.39px] w-4/12'>
                            <img className='w-full h-full' src="/images/prueba.jpg" alt="prueba" />
                          </div>
                          <div className='max-w-[173px] w-8/12'>
                            <div>
                              <h4 className='3xl:text-lg'>
                                Mikania micrantha
                              </h4>
                              <p className='text-sm mt-[13.8px]'>
                                <span className='font-barlow-condensed text-2xl 3xl:text-[32px] font-semibold'>13</span>
                                registros
                              </p>
                              <div className='flex mt-[14.6px]'>
                                <div className='w-1/3 h-[4px]' style={{ backgroundColor: '#93FF41' }}>&nbsp;</div>
                                <div className='w-1/3 h-[4px]' style={{ backgroundColor: '#FF4141' }}>&nbsp;</div>
                                <div className='w-1/3 h-[4px]' style={{ backgroundColor: '#FFB341' }}>&nbsp;</div>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div className='flex justify-between items-center mt-[35.52px] gap-x-4'>
                          <div className='max-w-[106.39px] w-4/12'>
                            <img className='w-full h-full' src="/images/prueba.jpg" alt="prueba" />
                          </div>
                          <div className='max-w-[173px] w-8/12'>
                            <div>
                              <h4 className='3xl:text-lg'>
                                Mikania micrantha
                              </h4>
                              <p className='text-sm mt-[13.8px]'>
                                <span className='font-barlow-condensed text-2xl 3xl:text-[32px] font-semibold'>13</span>
                                registros
                              </p>
                              <div className='flex mt-[14.6px]'>
                                <div className='w-1/3 h-[4px]' style={{ backgroundColor: '#93FF41' }}>&nbsp;</div>
                                <div className='w-1/3 h-[4px]' style={{ backgroundColor: '#FF4141' }}>&nbsp;</div>
                                <div className='w-1/3 h-[4px]' style={{ backgroundColor: '#FFB341' }}>&nbsp;</div>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div className='flex justify-between items-center mt-[35.52px] gap-x-4'>
                          <div className='max-w-[106.39px] w-4/12'>
                            <img className='w-full h-full' src="/images/prueba.jpg" alt="prueba" />
                          </div>
                          <div className='max-w-[173px] w-8/12'>
                            <div>
                              <h4 className='3xl:text-lg'>
                                Mikania micrantha
                              </h4>
                              <p className='text-sm mt-[13.8px]'>
                                <span className='font-barlow-condensed text-2xl 3xl:text-[32px] font-semibold'>13</span>
                                registros
                              </p>
                              <div className='flex mt-[14.6px]'>
                                <div className='w-1/3 h-[4px]' style={{ backgroundColor: '#93FF41' }}>&nbsp;</div>
                                <div className='w-1/3 h-[4px]' style={{ backgroundColor: '#FF4141' }}>&nbsp;</div>
                                <div className='w-1/3 h-[4px]' style={{ backgroundColor: '#FFB341' }}>&nbsp;</div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </MenuExplorer>
        </div>
      </div>

      {/* Arboles de navegacio */}
      <div className='py-12 bg-white-2'>
        <div className='mx-auto w-10/12 max-w-screen-xl'>
          <MenuExplorer tree={interestTree} search={searchBiologicTree}>
            <MenuExplorer.Title>
              <p className='3xl:text-lg'>
                Conoce las cifras por
              </p>
              <h2 className='font-black text-3xl 3xl:text-4xl'>
                Regiones
              </h2>
            </MenuExplorer.Title>
            <MenuExplorer.Tree className='relative mt-[45.52px]' />
            <MenuExplorer.Breadcrumb className=" flex items-center gap-x-2 mt-[30.8px] ml-5" />
            <div className='bg-white py-12 lg:py-16 xl:py-20'>
              <div className='text-center'>
                <h3 className='font-black text-2xl 3xl:text-3xl'>
                  Número de especies registradas por municipios de Nariño
                </h3>
              </div>
              <div className='mx-auto w-10/12 mt-10'>
                <div className='flex flex-col lg:flex-row items-center justify-between gap-y-8'>
                  <div className='lg:w-1/3 max-w-[216.31px]'>
                    <div className='text-center'>
                      <p className='font-barlow-condensed text-5xl 3xl:text-6xl font-semibold'>
                        86
                      </p>
                      <p className='3xl:text-lg'>
                        Especies amenazadas
                      </p>
                      <img className='mx-auto mt-[31.69px]' src="/images/cifras-chart-demo.svg" alt="cifras" />
                      <div className='mt-[25.4px] space-y-[7px]'>
                        <p className='text-sm'>
                          Lorem ipsum dolor sit
                        </p>
                        <p className='text-sm'>
                          Lorem ipsum dolor sit
                        </p>
                        <p className='text-sm'>
                          Lorem ipsum dolor sit
                        </p>
                      </div>
                    </div>
                  </div>
                  <div className='lg:w-1/3 max-w-[216.31px]'>
                    <div className='text-center'>
                      <p className='font-barlow-condensed text-5xl 3xl:text-6xl font-semibold'>
                        216
                      </p>
                      <p className='3xl:text-lg'>
                        Especies CITES
                      </p>
                      <img className='mx-auto mt-[31.69px]' src="/images/cifras-chart-demo.svg" alt="cifras" />
                      <div className='mt-[25.4px] space-y-[7px]'>
                        <p className='text-sm'>
                          Lorem ipsum dolor sit
                        </p>
                        <p className='text-sm'>
                          Lorem ipsum dolor sit
                        </p>
                        <p className='text-sm'>
                          Lorem ipsum dolor sit
                        </p>
                      </div>
                    </div>
                  </div>
                  <div className='lg:w-1/3 max-w-[216.31px]'>
                    <div className='text-center'>
                      <p className='font-barlow-condensed text-5xl 3xl:text-6xl font-semibold'>
                        41
                      </p>
                      <p className='3xl:text-lg'>
                        Especies endémicas
                      </p>
                      <img className='mx-auto mt-[31.69px]' src="/images/cifras-chart-demo.svg" alt="cifras" />
                      <div className='mt-[25.4px] space-y-[7px]'>
                        <p className='text-sm'>
                          Lorem ipsum dolor sit
                        </p>
                        <p className='text-sm'>
                          Lorem ipsum dolor sit
                        </p>
                        <p className='text-sm'>
                          Lorem ipsum dolor sit
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </MenuExplorer>
        </div>
      </div>

      <div className='py-12 lg:py-16 xl:py-20 bg-blue-green'>
        <div className='mx-auto w-10/12 max-w-screen-xl'>
          <h2 className='text-white font-black text-3xl 3xl:text-4xl'>
            Publicadores
          </h2>
          <div className='mt-[50px] relative'>
            <SimpleSlider buttonColor='light' slidesToScroll={4} slidesToShow={4} responsive>
              {
                publishersData.map((item, index) => {
                  return (
                    <div className='px-5' key={index}>
                      <PublishersCard {...item} />
                    </div>
                  )
                })
              }
            </SimpleSlider>
          </div>
          <div className='mt-10 text-center'>
            <a className='inline-block text-white border border-white rounded-[26px] py-3 px-[30px]' href="#">
              Conocer más
            </a>
          </div>
        </div>
      </div>

      <div className='py-12 lg:py-16 xl:py-20 bg-white-2'>
        <div className='mx-auto w-10/12 max-w-screen-xl'>
          <div className='mx-auto max-w-[507px] text-center'>
            <div className='space-y-6'>
              <h2 className='font-black text-3xl 3xl:text-4xl'>
                Explora Nariño
              </h2>
              <p className='3xl:text-lg'>
                Lorem ipsum dolor sit amet, cons ectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet.
              </p>
              <details>
                <summary className='inline-flex items-center gap-x-2 border border-black rounded-[26px] py-[14px] px-[51px] cursor-pointer'>
                  <p>
                    Cómo funciona esta herramienta
                  </p>
                  <img src="/images/arrow-app.svg" alt="arrow app" />
                </summary>
                <div className='mt-4'>
                  <p>
                    More info about the details.
                  </p>
                </div>
              </details>
            </div>
          </div>
          <div className='mt-[55.13px]'>
            <iframe className='h-screen w-full mx-auto' src="https://datasketch.shinyapps.io/sib-data-app/?region=narino"></iframe>
          </div>
        </div>
      </div>

      <div className='py-12 lg:py-16 xl:py-20 bg-white'>
        <div className='mx-auto w-10/12 lg:w-9/12 max-w-screen-xl'>
          <div className='grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6 gap-8'>
            <p className='font-bold text-lg 3xl:text-xl'>
              Con el apoyo de
            </p>
            <img className='h-[100px] mx-auto' src="/images/resguardo-integrado-logo.png" alt="resguardo integrado" />
            <img className='h-[100px] mx-auto' src="/images/reserva-natural-logo.png" alt="reserva natural" />
            <img className='h-[100px] mx-auto' src="/images/gobernacion-de-narino-logo.png" alt="gobernacion de narino" />
            <img className='h-[100px] mx-auto' src="/images/universidad-de-narino-logo.png" alt="universidad de narino" />
            <img className='h-[100px] mx-auto' src="/images/humboldt-logo.png" alt="humboldt" />
          </div>
        </div>
      </div>
    </>
  )
}
